[package]
org = "lenovo"
name = "server"
version = "0.1.0"
distribution = "2201.10.1"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerina"
name = "jwt"
version = "2.13.0"

[[dependency]]
org = "ballerinax"
name = "postgresql"
version = "1.13.1"

[[dependency]]
org = "ballerina"
name = "crypto"
version = "2.7.2"

[[dependency]]
org = "ballerina"
name = "sql"
version = "1.14.1"

[[dependency]]
org = "ballerina"
name = "time"
version="2.5.0"